# Generated by Django 4.1.5 on 2023-01-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inscripción"),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Nombre/s")),
                (
                    "last_name",
                    models.CharField(max_length=40, verbose_name="Apellido/s"),
                ),
                ("dni", models.IntegerField(verbose_name="DNI")),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ARG", "Argentina"),
                            ("BOL", "Boliviana"),
                            ("BRA", "Brasilera"),
                            ("CHI", "Chilena"),
                            ("COL", "Colombiana"),
                            ("ECU", "Ecuatoriana"),
                            ("PAR", "Paraguaya"),
                            ("PER", "Peruana"),
                            ("URU", "Uruguaya"),
                            ("VEN", "Venezolana"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=12,
                        verbose_name="Nacionalidad",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Femenino", "Femenino"),
                            ("Masculino", "Masculino"),
                            ("No Binario", "No Binario"),
                        ],
                        max_length=10,
                        verbose_name="Genero",
                    ),
                ),
                ("birthday", models.DateField(verbose_name="Fecha de nacimiento")),
                ("address", models.CharField(max_length=50, verbose_name="Domicilio")),
                (
                    "neighborhood",
                    models.CharField(
                        choices=[
                            ("Avellaneda", "Avellaneda"),
                            ("Barrio Pampa", "Barrio Pampa"),
                            ("Caraza", "Caraza"),
                            ("C.A.B.A.", "C.A.B.A."),
                            (
                                "El pueblito/Radio Estación",
                                "El pueblito/Radio Estación",
                            ),
                            ("Gerli", "Gerli"),
                            ("Lanús Este", "Lanús Este"),
                            ("Lanús Oeste", "Lanús Oeste"),
                            ("L. de Zamora", "L. de Zamora"),
                            ("Valentin Alsina", "Valentin Alsina"),
                            ("Villa Diamante", "Villa Diamante"),
                            ("Villa Jardín", "Villa Jardín"),
                        ],
                        max_length=30,
                        verbose_name="Localidad/Barrio",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                ("cellphone_1", models.CharField(max_length=10)),
                ("cellphone_2", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciónes",
            },
        ),
    ]
