# Generated by Django 4.1.5 on 2023-03-28 13:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campus", models.CharField(max_length=30, verbose_name="Sede")),
                ("address", models.CharField(max_length=35, verbose_name="Dirección")),
                ("referent", models.CharField(max_length=15, verbose_name="Referente")),
                ("phone_number", models.CharField(max_length=10)),
            ],
            options={"verbose_name": "Sede", "verbose_name_plural": "Sedes",},
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id_commission",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Comisión",
                    ),
                ),
                (
                    "commission",
                    models.CharField(max_length=15, verbose_name="Comisión"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Activa", "Activa"),
                            ("Reagrupada", "Reagrupada"),
                            ("Cerrada", "Cerrada"),
                            ("Egresada", "Egresada"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=models.SET("Sede Eliminada"), to="fines.campus"
                    ),
                ),
            ],
            options={"verbose_name": "Comisión", "verbose_name_plural": "Comisiones",},
        ),
        migrations.CreateModel(
            name="Orientation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orientation",
                    models.CharField(max_length=40, verbose_name="Orientación"),
                ),
                (
                    "resolution",
                    models.CharField(max_length=10, verbose_name="N° Resolución"),
                ),
            ],
            options={
                "verbose_name": "Orientación",
                "verbose_name_plural": "Orientaciones",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=40, verbose_name="Asignatura")),
                ("hours", models.IntegerField(verbose_name="Horas Cátedra")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("1°1C", "1°1C"),
                            ("1°2C", "1°2C"),
                            ("2°1C", "2°1C"),
                            ("2°2C", "2°2C"),
                            ("3°1C", "3°1C"),
                            ("3°2C", "3°2C"),
                        ],
                        max_length=4,
                        verbose_name="Cuatrimestre",
                    ),
                ),
                (
                    "orientation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fines.orientation",
                        verbose_name="Orientación",
                    ),
                ),
            ],
            options={"verbose_name": "Materias", "verbose_name_plural": "Materias",},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "dni",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999999),
                        ],
                        verbose_name="DNI",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre/s")),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Apellido/s"),
                ),
                ("birthday", models.DateField(verbose_name="Fecha de nacimiento")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F", "Femenino"),
                            ("M", "Masculino"),
                            ("X", "No Binario"),
                        ],
                        max_length=1,
                        verbose_name="Género",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ARG", "Argentina"),
                            ("BOL", "Boliviana"),
                            ("BRA", "Brasilera"),
                            ("CHI", "Chilena"),
                            ("COL", "Colombiana"),
                            ("ECU", "Ecuatoriana"),
                            ("PAR", "Paraguaya"),
                            ("PER", "Peruana"),
                            ("URU", "Uruguaya"),
                            ("VEN", "Venezolana"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=12,
                        verbose_name="Nacionalidad",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "cellphone",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999999999),
                        ],
                        verbose_name="Celular",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Inscripción"
                    ),
                ),
                (
                    "place_birdth",
                    models.CharField(
                        max_length=100, verbose_name="Lugar de Nacimiento"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Domicilio"
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        choices=[
                            ("Avellaneda", "Avellaneda"),
                            ("Barrio Pampa", "Barrio Pampa"),
                            ("Caraza", "Caraza"),
                            ("C.A.B.A.", "C.A.B.A."),
                            (
                                "El pueblito/Radio Estación",
                                "El pueblito/Radio Estación",
                            ),
                            ("Gerli", "Gerli"),
                            ("Lanús Este", "Lanús Este"),
                            ("Lanús Oeste", "Lanús Oeste"),
                            ("L. de Zamora", "L. de Zamora"),
                            ("Valentin Alsina", "Valentin Alsina"),
                            ("Villa Diamante", "Villa Diamante"),
                            ("Villa Jardín", "Villa Jardín"),
                        ],
                        max_length=30,
                        verbose_name="Localidad/Barrio",
                    ),
                ),
                (
                    "cellphone_2",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Celular 2"
                    ),
                ),
                (
                    "level_studies",
                    models.CharField(
                        choices=[
                            ("Primaria completa", "Primaria 6to o 7mo grado completo"),
                            (
                                "1ro de 6 años",
                                "1ro secundaria común de 6 años o técnica de 7 años",
                            ),
                            (
                                "2do de 6 años",
                                "2do secundaria común de 6 años o técnica de 7 años",
                            ),
                            (
                                "3ro de 6 años",
                                "3ro secundaria común de 6 años o técnica de 7 años",
                            ),
                            (
                                "4to de 6 años",
                                "4to secundaria común de 6 años o técnica de 7 años",
                            ),
                            (
                                "5to de 6 años",
                                "5to secundaria común de 6 años o técnica de 7 años",
                            ),
                            (
                                "1ro de 5 años",
                                "1ro secundaria común de 5 años o técnica de 6 años",
                            ),
                            (
                                "2do de 5 años",
                                "1ro secundaria común de 5 años o técnica de 6 años",
                            ),
                            (
                                "3ro de 5 años",
                                "1ro secundaria común de 5 años o técnica de 6 años",
                            ),
                            (
                                "4to de 5 años",
                                "1ro secundaria común de 5 años o técnica de 6 años",
                            ),
                            ("7mo EGB", "7mo año EGB"),
                            ("8vo EGB", "8vo año EGB"),
                            ("9no EGB", "9no año EGB"),
                            ("9no EGBA", "9no/3er ciclo EGB Adultos"),
                            ("1ro Polimodal", "1ro polimodal"),
                            ("2do Polimodal", "2do polimodal"),
                            ("1ro ESB", "1ro secundaria básica ESB"),
                            ("2do ESB", "2ro secundaria básica ESB"),
                            ("3ro ESB", "3ro secundaria básica ESB"),
                            ("1ro BAOT/BAO", "1ro BAOT/BAO"),
                            ("2do BAOT/BAO", "1ro BAOT/BAO"),
                        ],
                        max_length=20,
                        verbose_name="Estudios Previos",
                    ),
                ),
                (
                    "subjets_owed",
                    models.TextField(blank=True, verbose_name="Materias Adeudadas"),
                ),
                ("college", models.CharField(max_length=50, verbose_name="Colegio")),
                (
                    "college_country",
                    models.CharField(
                        choices=[
                            ("ARG", "Argentina"),
                            ("BOL", "Boliviana"),
                            ("BRA", "Brasilera"),
                            ("CHI", "Chilena"),
                            ("COL", "Colombiana"),
                            ("ECU", "Ecuatoriana"),
                            ("PAR", "Paraguaya"),
                            ("PER", "Peruana"),
                            ("URU", "Uruguaya"),
                            ("VEN", "Venezolana"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=12,
                        verbose_name="País del colegio",
                    ),
                ),
                (
                    "college_province",
                    models.CharField(
                        choices=[
                            ("Buenos Aires", "Buenos Aires"),
                            ("C.A.B.A.", "C.A.B.A."),
                            ("Otro país", "Otro país"),
                            ("Catamarca", "Catamarca"),
                            ("Chaco", "Chaco"),
                            ("Chubut", "Chubut"),
                            ("Cordoba", "Cordoba"),
                            ("Corrientes", "Corrientes"),
                            ("Entre Ríos", "Entre Ríos"),
                            ("Formosa", "Formosa"),
                            ("Jujuy", "Jujuy"),
                            ("La Pampa", "La Pampa"),
                            ("La Rioja", "La Rioja"),
                            ("Mendoza", "Mendoza"),
                            ("Misiones", "Misiones"),
                            ("Río Negro", "Río Negro"),
                            ("Salta", "Salta"),
                            ("San Juan", "San Juan"),
                            ("San Luis", "San Luis"),
                            ("Santa Cruz", "Santa Cruz"),
                            ("Santa Fé", "Santa Fé"),
                            ("Santiago del Estero", "Santiago del Estero"),
                            (
                                "Tierra del Fuego e Islas del Sur",
                                "Tierra del Fuego e Islas del Sur",
                            ),
                            ("Tucuman", "Tucuman"),
                        ],
                        max_length=35,
                        verbose_name="Provincia del colegio",
                    ),
                ),
                (
                    "college_city",
                    models.CharField(max_length=30, verbose_name="Ciudad del colegio"),
                ),
                (
                    "prefered_shift",
                    models.CharField(
                        choices=[
                            ("TM", "Turno Mañana 8 hs a 12 hs aprox."),
                            ("TT", "Turno Tarde 13 hs a 17 hs aprox."),
                            ("TV", "Turno Vespertino/Noche 18 hs a 22 hs aprox."),
                        ],
                        max_length=45,
                        verbose_name="Turno de preferencia",
                    ),
                ),
                (
                    "prefered_campus",
                    models.CharField(max_length=30, verbose_name="Sede de preferencia"),
                ),
                ("commission", models.ManyToManyField(to="fines.commission")),
            ],
            options={"verbose_name": "Alumno", "verbose_name_plural": "Alumnos",},
        ),
        migrations.CreateModel(
            name="Legajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book", models.IntegerField(verbose_name="Libro")),
                ("folio", models.IntegerField(verbose_name="Folio")),
                ("dni_copy", models.BooleanField(verbose_name="DNI Copia")),
                ("p_nac_copy", models.BooleanField(verbose_name="P. Nac. Copia")),
                (
                    "certified",
                    models.BooleanField(verbose_name="Certificado de estudios"),
                ),
                ("constancia", models.BooleanField(verbose_name="Constancia")),
                ("obs", models.TextField(verbose_name="Observaciones")),
                (
                    "orientation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fines.orientation",
                        verbose_name="Orientación",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fines.student",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={"verbose_name": "Legajo", "verbose_name_plural": "Legajos",},
        ),
        migrations.AddField(
            model_name="commission",
            name="orientation",
            field=models.ForeignKey(
                on_delete=models.SET("Orientación Eliminada"), to="fines.orientation"
            ),
        ),
    ]
