# Generated by Django 4.1.5 on 2023-01-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscription",
            name="address",
            field=models.CharField(blank=True, max_length=50, verbose_name="Domicilio"),
        ),
    ]
